name: release

on:
  push:
    branches:
      - "*.x"
      - main
      - beta

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write
  packages: read

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      # build local version to create token
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json

      - run: npm ci
      - run: npm run build
      - uses: ./
        id: app-token
      # install release dependencies and release
      - run: |
          echo "@matherm-aboehm:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com:_authToken=${NPM_TOKEN}" >> ~/.npmrc
          npm install --no-save @matherm-aboehm/semantic-release-github-commit semantic-release-plugin-github-breaking-version-tag
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npx semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
